### ISSUE TITLE
A resident  can add move in information

### ISSUE THREAD

**Issue by jpost27** [java24july-ank-meh/homes#31]

**Comment by HurielHernandez** [comment]
Cannot send and convert date from angularjs to Java Date.  Tried create a work around different ways with no luck.  Possible fix could be to temporarily change moveInDate to type String . 
{
  "timestamp": 1506312451458,
  "status": 400,
  "error": "Bad Request",
  "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
  "message": "JSON parse error: Can not construct instance of java.time.LocalDateTime: no String-argument constructor/factory method to deserialize from String value ('2017-09-25'); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.time.LocalDateTime: no String-argument constructor/factory method to deserialize from String value ('2017-09-25')\n at [Source: java.io.PushbackInputStream@1b8fc456; line: 14, column: 17] (through reference chain: com.revature.application.model.Associate[\"moveInDate\"])",
  "path": "/associates/createOrUpdate"
}
