### ISSUE TITLE
Incorrect data type returned when updating Unit from /api/slack/unit/channelName/{name}/1190R/105

### ISSUE THREAD

**Issue by HurielHernandez** [java24july-ank-meh/homes#63]
Calling this end point: 
`http://107.22.129.162:8088/unit/channelName/Westerly%20at%20Worldgate%20Apartments/1190R/105
`
returns:
`westerlyat1190R-105
` as plain text instead of JSON.

This causes angularJs to show an error even though the Unit was updated properly

**Comment by palmour** [comment]
My bad. The unit/channelName and complex/channelName endpoints should return JSON now. The change is on dev.
